install.packages('readr')
install.packages('plyr',repos = "http://cran.us.r-project.org")
install.packages('tidyr')
install.packages('dplyr')
install.packages('rvest')
library(plyr)
library(tidyr)
library(dplyr)
library(rvest)
library(readr)
url_list2 <- read_csv("https://raw.githubusercontent.com/azoezoe/data/master/url_list2.csv")
IFCN5<-data.frame()
g<-url_list2$url
for(g in url_list2$url){
  html<-read_html(g,encoding="UTF-8")
  by<-html_text(html_nodes(html,'.entry-content__text--org'))
  date_country<-html_text(html_nodes(html,'strong'))
  trueorfalse<-html_text(html_nodes(html,'.entry-title--red'))
  title<-html_text(html_nodes(html,'.entry-title'))
  content<-html_text(html_nodes(html,'.entry-content__text--explanation'))
  url<-html_attr(html_nodes(html,".entry-content__button--smaller"),"href")
  platform<-html_text(html_nodes(html,'.entry-content__button--smaller+ .entry-content__text--smaller'))
  Sys.sleep(15)
  IFCN5<-rbind(IFCN5,data.frame(by=by,date_country=date_country,trueorfalse=trueorfalse,title=title,content=content,url=url,platform=platform))
}
write.csv(IFCN5,"./IFCN5.csv",row.names = FALSE)