install.packages('readr')
install.packages('plyr',repos = "http://cran.us.r-project.org")
install.packages('tidyr')
install.packages('dplyr')
install.packages('rvest')
library(plyr)
library(tidyr)
library(dplyr)
library(rvest)
library(readr)
url_list2 <- read_csv("https://raw.githubusercontent.com/azoezoe/data/master/url_list2.csv")

i=url_list2$url
IFCN<-data.frame()
for(i in url_list2$url){
  html<-read_html(i,encoding="UTF-8")
  by<-html_text(html_nodes(html,'.entry-content__text--org'))
  date_country<-html_text(html_nodes(html,'strong'))
  trueorfalse<-html_text(html_nodes(html,'.entry-title--red'))
  title<-html_text(html_nodes(html,'.entry-title'))
  content<-html_text(html_nodes(html,'.entry-content__text--explanation'))
  url<-html_attr(html_nodes(html,".entry-content__button--smaller"),"href")
  platform<-html_text(html_nodes(html,'.entry-content__button--smaller+ .entry-content__text--smaller'))
  Sys.sleep(10)
  temp<-data.frame(by=by,date_country=date_country,trueorfalse=trueorfalse,title=title,content=content,url=url,platform=platform)
  IFCN<-rbind(IFCN,temp)
  
  write.csv(IFCN,"./IFCN.csv",row.names = FALSE)